### ISSUE TITLE
Can't post to server

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/full-stack-project#525]
I was getting a 'bad request' when trying to post from the front end so I went to do automated testing and, as expected, posting failed the test, but also failed for another table that succeeded yesterday. Additionally, the GET is also not passing on either, but is working in the app. I'm getting no useable information from the rake test and need help.

```
  1) Cards API GET /cards lists all cards
     Failure/Error: expect(cards_response.first['name']).to eq(card['name'])
     
     TypeError:
       no implicit conversion of String into Integer
     # ./spec/requests/cards_spec.rb:52:in `[]'
     # ./spec/requests/cards_spec.rb:52:in `block (3 levels) in <top (required)>'

  2) Cards API GET /cards/:id shows one card
     Failure/Error: expect(card_response['id']).not_to be_nil
     
       expected: not nil
            got: nil
     # ./spec/requests/cards_spec.rb:66:in `block (3 levels) in <top (required)>'

  3) Cards API POST /cards creates a card
     Failure/Error: expect(card_response['id']).not_to be_nil
     
       expected: not nil
            got: nil
     # ./spec/requests/cards_spec.rb:111:in `block (3 levels) in <top (required)>'

  4) Decks API GET /decks lists all decks
     Failure/Error: expect(decks_response.first['name']).to eq(deck['name'])
     
     TypeError:
       no implicit conversion of String into Integer
     # ./spec/requests/decks_spec.rb:52:in `[]'
     # ./spec/requests/decks_spec.rb:52:in `block (3 levels) in <top (required)>'

  5) Decks API GET /decks/:id shows one deck
     Failure/Error: expect(deck_response['id']).not_to be_nil
     
       expected: not nil
            got: nil
     # ./spec/requests/decks_spec.rb:66:in `block (3 levels) in <top (required)>'

  6) Decks API POST /decks creates a deck
     Failure/Error: expect(deck_response['id']).not_to be_nil
     
       expected: not nil
            got: nil
     # ./spec/requests/decks_spec.rb:111:in `block (3 levels) in <top (required)>'
```
