### ISSUE TITLE
Linter error when renaming project database

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#574]
Anyone run into this linter issue when doing step 7 of the project database? Renaming project database.
![image](https://cloud.githubusercontent.com/assets/24688275/22957875/6959b602-f2f9-11e6-88f3-a4ed2f3e3d9b.png)

**Comment by jrhorn424** [comment]
Please post the contents of your `.rubocop.yml` file.

You should not get this error if you started from our template, so I may have to continue debugging this with you.

**Comment by raq929** [comment]
Ash, has this been resolved? If yes, please let us know how you resolved it, and close the issue. If not, please post an update. Thanks!

**Comment by AshlenPrice** [comment]
Sorry for the delay on this. When I open the file in atom it's not giving me the error anymore but here is the code from the `.rubocop.yml` file
```yml
Style/Documentation:
  Exclude:
    - 'app/**/*'
    - 'db/migrate/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  TargetRubyVersion:
    2.3
  Exclude:
    - 'bin/*'
    - 'config/database.yml'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
```
