### ISSUE TITLE
[scss] - index.scss file is not loading

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/full-stack-project#827]
My styles aren't working when I grunt server to local host or when open my index.html manually.
If I comment out my css nothing happens. 

Webpack compiles successfully, no errors.

I am requiring index.scss in my index.js file.

```js
require('./assets/styles/index.scss')
```

I have NPM installed. I didn't start with a fresh js-template. I downloaded my tic tac toe project from github and made a new repository locally. I wanted to re use the authentication code from it.

this is my index.scss file.

```scss
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
@import 'fonts';

body {
  font-family: $main-font;
}

.form-signin {
  margin: 0 auto;
  max-width: 330px;
  padding: 15px;
}

.game-board {
  font-size: 88px;
  text-align: center;
}

#form-signout {
  display: none;
  margin: 0 auto;
  max-width: 200px;
  padding: 15px;
}

.start-hidden {
  display: none;
}

#start-game {
  margin: 0 auto;
  display: none;
  max-width: 200px;
  padding: 15px;
}

.black-border {
  border: solid 1px black;
  height: 100px;
}

.board-cell {
  height: 100px;
}

h2 {
  text-align: center;
}

#get-games {
  max-width: 200px;
  padding: 15px;
  margin: 0 auto;
}

.padding {
  height: 300px;
}

.hide-board {
  display: none;
}
```

Any tips on where to start? I wasn't sure what to type in google because the issue may be specific to this template.
